server:
  port: 8080
  servlet-path: /

# Set the file size limit (default 1Mb). If you want to specify that files be
# unlimited set the multipart.maxFileSize property to -1.
multipart.maxFileSize: 3Mb

# Set the total request size for a multipart/form-data (default 10Mb)
multipart.maxRequestSize: 20Mb

mvc:
  view:
    # Content Type encoding.
    content-type: text/html;charset=UTF-8
    # View name prefix (path relative to the project.directory).
    prefix: /views/
    # View name suffix.
    suffix: .jsp
    # It is exposed context beans as attributes.
    expose-context-beans-as-attributes: true
  resource:
    # URL of resources (path relative to the view.name-prefix).
    path-pattern: /resources/**
    # Location of resources (path relative to the view.name-prefix).
    resource-location: /resources/

database:
  jdbc:
    # The url of driver for connection to the database.
    url: jdbc:postgresql://localhost:5432/portfolio
    # The user name which will be work with database.
    username: postgres
    # The user password which will be work with database.
    password: postgres
    # The driver for connection to the database.
    driver-class-name: org.postgresql.Driver

    connection-properties: >
      useSSL=false;
      useUnicode=true;
      characterEncoding=UTF-8;
      useJDBCCompliantTimezoneShift=true;
      useJDBCCompliantTimezoneShift=true;
      useLegacyDatetimeCode=false;
      serverTimezone=GMT

    # The initial size of the connection pool.
    initial-size: 10
    # The maximum number of active connections that
    # can be allocated at the same time.
    max-active: 50
    # This property determines whether or not the pool will
    # validate objects before they are borrowed from the pool.
    test-on-borrow: true
    # The SQL query that will be used to validate connections
    #from this pool before returning them to the caller.
    validation-query: SELECT 1

  hibernate:
    # An Hibernate SQL dialect for database.
    dialect: org.hibernate.dialect.PostgreSQL94Dialect
    # It is show sql in the console.
    show-sql: false
    # It is use DDL.
    generate-ddl: true
    # The packages of entity for Entity Manager.
    packages-to-scan: ru.zolotarev.portfolio.repository.entity

security:
  page:
    admin: /admin/**
    login: /login
    access-deny: /access_deny
  default-success:
    page: /admin/
    always-use: true
  admin:
    login: admin
    password: 123
  user:
    login: user
    password: 123456